### ISSUE TITLE
Listing some cool Charts?

### ISSUE THREAD

**Issue by florianrusch** [cdwv/awesome-helm#1]
Hi @andrzejwp 

wouldn't it be cool to list some awesome charts?
For example I found this one: https://github.com/wongnai/kube-slack

**Comment by andrzejwp** [comment]
Cool! Would you mind verifying if it is not already listed under one of the links in the Hubs section?
If not - would you mind opening a PR with that chart linked under the 3rd party charts section?

Thanks!

Andrzej WP
