### ISSUE TITLE
Add Helm Chart Playground Editor?

### ISSUE THREAD

**Issue by tobiashochguertel** [cdwv/awesome-helm#50]
I developed a tool to edit Helm Charts with a preview of the rendered chart. The project can be found here: https://github.com/tobiashochguertel/th-helm-playground-frontend

**Comment by andrzejwp** [comment]
Hi @tobiashochguertel thank you for the contribution, I will be happy to include your project once it gains a bit more momentum. As per other "awesome-xxx" lists - we accept links to projects that are generally useful to the community. I understand that it's a bit of a chicken and egg problem ;-)
Can you please re-open the PR once your repo gains at least 10 stargazers?

thank you
